server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sms_db
    username: aaron
    password: aaron
  jpa:
    show-sql: true
    hibernate:
      dll-auto: create
      show: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
